include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - parameter_assignments

analyzer:
  errors:
    prefer_single_quotes: error
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
