name: cooking_home
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  injectable: ^1.5.3
  get_it: ^7.2.0
  logging: ^1.0.2
  equatable: ^2.0.3
  google_fonts: ^3.0.1
  lottie: ^1.4.1
  flutter_feather_icons: ^2.0.0+1
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mocktail: ^0.3.0
  injectable_generator: ^1.5.4
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
