name: Cooking Home App Pull Requests
on:
  push:
    branches: [main]

jobs:
  analyze_and_test:
    name: flutter analyze and tests
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: "12.x"
      FLUTTER_VERSION: "3.0.5"

    steps:
      - name: Get Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Run Flutter formatt code
        run: flutter format --dry-run --set-exit-if-changed lib/
      - run: flutter format --dry-run --set-exit-if-changed test/

      - name: Run Flutter Unit Tests
        run: flutter test
